### ISSUE TITLE
The run commond  is wrong

### ISSUE THREAD

**Issue by Css22** [Raphael-Hao/Abacus#2]
**Question:**
When I tried to profile using the commands you provided, I found that most of them had errors. They are missing key parameters.

**Example**

![Snipaste_2023-04-11_14-00-52](https://user-images.githubusercontent.com/75296205/231069901-9380771e-3fee-49d5-8615-5b140968ebb6.png)

**Comment by Raphael-Hao** [comment]
You can add appropriate command parameters according to your hardware environment, such as `--platform single --gpu A100, --device 0`. And then these problems should be fixed.
